language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
before_script: composer install
script: phpunit --configuration test/phpunit.xml
notifications:
  email:
    on_success: always
    on_failure: always
